// Code generated by "enumer -type=Locale -linecomment -json"; DO NOT EDIT.

package azuretexttospeech

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _LocaleName = "af-ZAam-ETar-AEar-BHar-DZar-EGar-IQar-JOar-KWar-LYar-MAar-QAar-SAar-SYar-TNar-YEbg-BGbn-BDca-EScs-CZcy-GBda-DKde-ATde-CHde-DEel-GRen-AUen-CAen-GBen-HKen-IEen-INen-KEen-NGen-NZen-PHen-SGen-TZen-USen-ZAes-ARes-BOes-CLes-COes-CRes-CUes-DOes-ECes-ESes-GQes-GTes-HNes-MXes-NIes-PAes-PEes-PRes-PYes-SVes-USes-UYes-VEet-EEfa-IRfi-FIil-PHfr-BEfr-CAfr-CHfr-FRga-IEgl-ESgu-INhe-ILhi-INhr-HRhu-HUid-IDit-ITja-JPjv-IDkm-KHko-KRlt-LTlv-LVmr-INms-MYmt-MTmy-MMnb-NOnl-BEnl-NLpl-PLpt-BRpt-PTro-ROru-RUsk-SKsl-SIso-SOsu-IDsv-SEsw-KEsw-TZta-INta-LKta-SGte-INth-THtr-TRuk-UAur-INur-PKuz-UZvi-VNzh-CNzh-HKzh-TWzu-ZA"

var _LocaleIndex = [...]uint16{0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190, 195, 200, 205, 210, 215, 220, 225, 230, 235, 240, 245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300, 305, 310, 315, 320, 325, 330, 335, 340, 345, 350, 355, 360, 365, 370, 375, 380, 385, 390, 395, 400, 405, 410, 415, 420, 425, 430, 435, 440, 445, 450, 455, 460, 465, 470, 475, 480, 485, 490, 495, 500, 505, 510, 515, 520, 525, 530, 535, 540, 545, 550, 555, 560, 565, 570, 575, 580, 585, 590, 595}

const _LocaleLowerName = "af-zaam-etar-aear-bhar-dzar-egar-iqar-joar-kwar-lyar-maar-qaar-saar-syar-tnar-yebg-bgbn-bdca-escs-czcy-gbda-dkde-atde-chde-deel-gren-auen-caen-gben-hken-ieen-inen-keen-ngen-nzen-phen-sgen-tzen-usen-zaes-ares-boes-cles-coes-cres-cues-does-eces-eses-gqes-gtes-hnes-mxes-nies-paes-pees-pres-pyes-sves-uses-uyes-veet-eefa-irfi-fiil-phfr-befr-cafr-chfr-frga-iegl-esgu-inhe-ilhi-inhr-hrhu-huid-idit-itja-jpjv-idkm-khko-krlt-ltlv-lvmr-inms-mymt-mtmy-mmnb-nonl-benl-nlpl-plpt-brpt-ptro-roru-rusk-sksl-siso-sosu-idsv-sesw-kesw-tzta-inta-lkta-sgte-inth-thtr-truk-uaur-inur-pkuz-uzvi-vnzh-cnzh-hkzh-twzu-za"

func (i Locale) String() string {
	if i < 0 || i >= Locale(len(_LocaleIndex)-1) {
		return fmt.Sprintf("Locale(%d)", i)
	}
	return _LocaleName[_LocaleIndex[i]:_LocaleIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _LocaleNoOp() {
	var x [1]struct{}
	_ = x[LocaleafZA-(0)]
	_ = x[LocaleamET-(1)]
	_ = x[LocalearAE-(2)]
	_ = x[LocalearBH-(3)]
	_ = x[LocalearDZ-(4)]
	_ = x[LocalearEG-(5)]
	_ = x[LocalearIQ-(6)]
	_ = x[LocalearJO-(7)]
	_ = x[LocalearKW-(8)]
	_ = x[LocalearLY-(9)]
	_ = x[LocalearMA-(10)]
	_ = x[LocalearQA-(11)]
	_ = x[LocalearSA-(12)]
	_ = x[LocalearSY-(13)]
	_ = x[LocalearTN-(14)]
	_ = x[LocalearYE-(15)]
	_ = x[LocalebgBG-(16)]
	_ = x[LocalebnBD-(17)]
	_ = x[LocalecaES-(18)]
	_ = x[LocalecsCZ-(19)]
	_ = x[LocalecyGB-(20)]
	_ = x[LocaledaDK-(21)]
	_ = x[LocaledeAT-(22)]
	_ = x[LocaledeCH-(23)]
	_ = x[LocaledeDE-(24)]
	_ = x[LocaleelGR-(25)]
	_ = x[LocaleenAU-(26)]
	_ = x[LocaleenCA-(27)]
	_ = x[LocaleenGB-(28)]
	_ = x[LocaleenHK-(29)]
	_ = x[LocaleenIE-(30)]
	_ = x[LocaleenIN-(31)]
	_ = x[LocaleenKE-(32)]
	_ = x[LocaleenNG-(33)]
	_ = x[LocaleenNZ-(34)]
	_ = x[LocaleenPH-(35)]
	_ = x[LocaleenSG-(36)]
	_ = x[LocaleenTZ-(37)]
	_ = x[LocaleenUS-(38)]
	_ = x[LocaleenZA-(39)]
	_ = x[LocaleesAR-(40)]
	_ = x[LocaleesBO-(41)]
	_ = x[LocaleesCL-(42)]
	_ = x[LocaleesCO-(43)]
	_ = x[LocaleesCR-(44)]
	_ = x[LocaleesCU-(45)]
	_ = x[LocaleesDO-(46)]
	_ = x[LocaleesEC-(47)]
	_ = x[LocaleesES-(48)]
	_ = x[LocaleesGQ-(49)]
	_ = x[LocaleesGT-(50)]
	_ = x[LocaleesHN-(51)]
	_ = x[LocaleesMX-(52)]
	_ = x[LocaleesNI-(53)]
	_ = x[LocaleesPA-(54)]
	_ = x[LocaleesPE-(55)]
	_ = x[LocaleesPR-(56)]
	_ = x[LocaleesPY-(57)]
	_ = x[LocaleesSV-(58)]
	_ = x[LocaleesUS-(59)]
	_ = x[LocaleesUY-(60)]
	_ = x[LocaleesVE-(61)]
	_ = x[LocaleetEE-(62)]
	_ = x[LocalefaIR-(63)]
	_ = x[LocalefiFI-(64)]
	_ = x[LocalefilPH-(65)]
	_ = x[LocalefrBE-(66)]
	_ = x[LocalefrCA-(67)]
	_ = x[LocalefrCH-(68)]
	_ = x[LocalefrFR-(69)]
	_ = x[LocalegaIE-(70)]
	_ = x[LocaleglES-(71)]
	_ = x[LocaleguIN-(72)]
	_ = x[LocaleheIL-(73)]
	_ = x[LocalehiIN-(74)]
	_ = x[LocalehrHR-(75)]
	_ = x[LocalehuHU-(76)]
	_ = x[LocaleidID-(77)]
	_ = x[LocaleitIT-(78)]
	_ = x[LocalejaJP-(79)]
	_ = x[LocalejvID-(80)]
	_ = x[LocalekmKH-(81)]
	_ = x[LocalekoKR-(82)]
	_ = x[LocaleltLT-(83)]
	_ = x[LocalelvLV-(84)]
	_ = x[LocalemrIN-(85)]
	_ = x[LocalemsMY-(86)]
	_ = x[LocalemtMT-(87)]
	_ = x[LocalemyMM-(88)]
	_ = x[LocalenbNO-(89)]
	_ = x[LocalenlBE-(90)]
	_ = x[LocalenlNL-(91)]
	_ = x[LocaleplPL-(92)]
	_ = x[LocaleptBR-(93)]
	_ = x[LocaleptPT-(94)]
	_ = x[LocaleroRO-(95)]
	_ = x[LocaleruRU-(96)]
	_ = x[LocaleskSK-(97)]
	_ = x[LocaleslSI-(98)]
	_ = x[LocalesoSO-(99)]
	_ = x[LocalesuID-(100)]
	_ = x[LocalesvSE-(101)]
	_ = x[LocaleswKE-(102)]
	_ = x[LocaleswTZ-(103)]
	_ = x[LocaletaIN-(104)]
	_ = x[LocaletaLK-(105)]
	_ = x[LocaletaSG-(106)]
	_ = x[LocaleteIN-(107)]
	_ = x[LocalethTH-(108)]
	_ = x[LocaletrTR-(109)]
	_ = x[LocaleukUA-(110)]
	_ = x[LocaleurIN-(111)]
	_ = x[LocaleurPK-(112)]
	_ = x[LocaleuzUZ-(113)]
	_ = x[LocaleviVN-(114)]
	_ = x[LocalezhCN-(115)]
	_ = x[LocalezhHK-(116)]
	_ = x[LocalezhTW-(117)]
	_ = x[LocalezuZA-(118)]
}

var _LocaleValues = []Locale{LocaleafZA, LocaleamET, LocalearAE, LocalearBH, LocalearDZ, LocalearEG, LocalearIQ, LocalearJO, LocalearKW, LocalearLY, LocalearMA, LocalearQA, LocalearSA, LocalearSY, LocalearTN, LocalearYE, LocalebgBG, LocalebnBD, LocalecaES, LocalecsCZ, LocalecyGB, LocaledaDK, LocaledeAT, LocaledeCH, LocaledeDE, LocaleelGR, LocaleenAU, LocaleenCA, LocaleenGB, LocaleenHK, LocaleenIE, LocaleenIN, LocaleenKE, LocaleenNG, LocaleenNZ, LocaleenPH, LocaleenSG, LocaleenTZ, LocaleenUS, LocaleenZA, LocaleesAR, LocaleesBO, LocaleesCL, LocaleesCO, LocaleesCR, LocaleesCU, LocaleesDO, LocaleesEC, LocaleesES, LocaleesGQ, LocaleesGT, LocaleesHN, LocaleesMX, LocaleesNI, LocaleesPA, LocaleesPE, LocaleesPR, LocaleesPY, LocaleesSV, LocaleesUS, LocaleesUY, LocaleesVE, LocaleetEE, LocalefaIR, LocalefiFI, LocalefilPH, LocalefrBE, LocalefrCA, LocalefrCH, LocalefrFR, LocalegaIE, LocaleglES, LocaleguIN, LocaleheIL, LocalehiIN, LocalehrHR, LocalehuHU, LocaleidID, LocaleitIT, LocalejaJP, LocalejvID, LocalekmKH, LocalekoKR, LocaleltLT, LocalelvLV, LocalemrIN, LocalemsMY, LocalemtMT, LocalemyMM, LocalenbNO, LocalenlBE, LocalenlNL, LocaleplPL, LocaleptBR, LocaleptPT, LocaleroRO, LocaleruRU, LocaleskSK, LocaleslSI, LocalesoSO, LocalesuID, LocalesvSE, LocaleswKE, LocaleswTZ, LocaletaIN, LocaletaLK, LocaletaSG, LocaleteIN, LocalethTH, LocaletrTR, LocaleukUA, LocaleurIN, LocaleurPK, LocaleuzUZ, LocaleviVN, LocalezhCN, LocalezhHK, LocalezhTW, LocalezuZA}

var _LocaleNameToValueMap = map[string]Locale{
	_LocaleName[0:5]:          LocaleafZA,
	_LocaleLowerName[0:5]:     LocaleafZA,
	_LocaleName[5:10]:         LocaleamET,
	_LocaleLowerName[5:10]:    LocaleamET,
	_LocaleName[10:15]:        LocalearAE,
	_LocaleLowerName[10:15]:   LocalearAE,
	_LocaleName[15:20]:        LocalearBH,
	_LocaleLowerName[15:20]:   LocalearBH,
	_LocaleName[20:25]:        LocalearDZ,
	_LocaleLowerName[20:25]:   LocalearDZ,
	_LocaleName[25:30]:        LocalearEG,
	_LocaleLowerName[25:30]:   LocalearEG,
	_LocaleName[30:35]:        LocalearIQ,
	_LocaleLowerName[30:35]:   LocalearIQ,
	_LocaleName[35:40]:        LocalearJO,
	_LocaleLowerName[35:40]:   LocalearJO,
	_LocaleName[40:45]:        LocalearKW,
	_LocaleLowerName[40:45]:   LocalearKW,
	_LocaleName[45:50]:        LocalearLY,
	_LocaleLowerName[45:50]:   LocalearLY,
	_LocaleName[50:55]:        LocalearMA,
	_LocaleLowerName[50:55]:   LocalearMA,
	_LocaleName[55:60]:        LocalearQA,
	_LocaleLowerName[55:60]:   LocalearQA,
	_LocaleName[60:65]:        LocalearSA,
	_LocaleLowerName[60:65]:   LocalearSA,
	_LocaleName[65:70]:        LocalearSY,
	_LocaleLowerName[65:70]:   LocalearSY,
	_LocaleName[70:75]:        LocalearTN,
	_LocaleLowerName[70:75]:   LocalearTN,
	_LocaleName[75:80]:        LocalearYE,
	_LocaleLowerName[75:80]:   LocalearYE,
	_LocaleName[80:85]:        LocalebgBG,
	_LocaleLowerName[80:85]:   LocalebgBG,
	_LocaleName[85:90]:        LocalebnBD,
	_LocaleLowerName[85:90]:   LocalebnBD,
	_LocaleName[90:95]:        LocalecaES,
	_LocaleLowerName[90:95]:   LocalecaES,
	_LocaleName[95:100]:       LocalecsCZ,
	_LocaleLowerName[95:100]:  LocalecsCZ,
	_LocaleName[100:105]:      LocalecyGB,
	_LocaleLowerName[100:105]: LocalecyGB,
	_LocaleName[105:110]:      LocaledaDK,
	_LocaleLowerName[105:110]: LocaledaDK,
	_LocaleName[110:115]:      LocaledeAT,
	_LocaleLowerName[110:115]: LocaledeAT,
	_LocaleName[115:120]:      LocaledeCH,
	_LocaleLowerName[115:120]: LocaledeCH,
	_LocaleName[120:125]:      LocaledeDE,
	_LocaleLowerName[120:125]: LocaledeDE,
	_LocaleName[125:130]:      LocaleelGR,
	_LocaleLowerName[125:130]: LocaleelGR,
	_LocaleName[130:135]:      LocaleenAU,
	_LocaleLowerName[130:135]: LocaleenAU,
	_LocaleName[135:140]:      LocaleenCA,
	_LocaleLowerName[135:140]: LocaleenCA,
	_LocaleName[140:145]:      LocaleenGB,
	_LocaleLowerName[140:145]: LocaleenGB,
	_LocaleName[145:150]:      LocaleenHK,
	_LocaleLowerName[145:150]: LocaleenHK,
	_LocaleName[150:155]:      LocaleenIE,
	_LocaleLowerName[150:155]: LocaleenIE,
	_LocaleName[155:160]:      LocaleenIN,
	_LocaleLowerName[155:160]: LocaleenIN,
	_LocaleName[160:165]:      LocaleenKE,
	_LocaleLowerName[160:165]: LocaleenKE,
	_LocaleName[165:170]:      LocaleenNG,
	_LocaleLowerName[165:170]: LocaleenNG,
	_LocaleName[170:175]:      LocaleenNZ,
	_LocaleLowerName[170:175]: LocaleenNZ,
	_LocaleName[175:180]:      LocaleenPH,
	_LocaleLowerName[175:180]: LocaleenPH,
	_LocaleName[180:185]:      LocaleenSG,
	_LocaleLowerName[180:185]: LocaleenSG,
	_LocaleName[185:190]:      LocaleenTZ,
	_LocaleLowerName[185:190]: LocaleenTZ,
	_LocaleName[190:195]:      LocaleenUS,
	_LocaleLowerName[190:195]: LocaleenUS,
	_LocaleName[195:200]:      LocaleenZA,
	_LocaleLowerName[195:200]: LocaleenZA,
	_LocaleName[200:205]:      LocaleesAR,
	_LocaleLowerName[200:205]: LocaleesAR,
	_LocaleName[205:210]:      LocaleesBO,
	_LocaleLowerName[205:210]: LocaleesBO,
	_LocaleName[210:215]:      LocaleesCL,
	_LocaleLowerName[210:215]: LocaleesCL,
	_LocaleName[215:220]:      LocaleesCO,
	_LocaleLowerName[215:220]: LocaleesCO,
	_LocaleName[220:225]:      LocaleesCR,
	_LocaleLowerName[220:225]: LocaleesCR,
	_LocaleName[225:230]:      LocaleesCU,
	_LocaleLowerName[225:230]: LocaleesCU,
	_LocaleName[230:235]:      LocaleesDO,
	_LocaleLowerName[230:235]: LocaleesDO,
	_LocaleName[235:240]:      LocaleesEC,
	_LocaleLowerName[235:240]: LocaleesEC,
	_LocaleName[240:245]:      LocaleesES,
	_LocaleLowerName[240:245]: LocaleesES,
	_LocaleName[245:250]:      LocaleesGQ,
	_LocaleLowerName[245:250]: LocaleesGQ,
	_LocaleName[250:255]:      LocaleesGT,
	_LocaleLowerName[250:255]: LocaleesGT,
	_LocaleName[255:260]:      LocaleesHN,
	_LocaleLowerName[255:260]: LocaleesHN,
	_LocaleName[260:265]:      LocaleesMX,
	_LocaleLowerName[260:265]: LocaleesMX,
	_LocaleName[265:270]:      LocaleesNI,
	_LocaleLowerName[265:270]: LocaleesNI,
	_LocaleName[270:275]:      LocaleesPA,
	_LocaleLowerName[270:275]: LocaleesPA,
	_LocaleName[275:280]:      LocaleesPE,
	_LocaleLowerName[275:280]: LocaleesPE,
	_LocaleName[280:285]:      LocaleesPR,
	_LocaleLowerName[280:285]: LocaleesPR,
	_LocaleName[285:290]:      LocaleesPY,
	_LocaleLowerName[285:290]: LocaleesPY,
	_LocaleName[290:295]:      LocaleesSV,
	_LocaleLowerName[290:295]: LocaleesSV,
	_LocaleName[295:300]:      LocaleesUS,
	_LocaleLowerName[295:300]: LocaleesUS,
	_LocaleName[300:305]:      LocaleesUY,
	_LocaleLowerName[300:305]: LocaleesUY,
	_LocaleName[305:310]:      LocaleesVE,
	_LocaleLowerName[305:310]: LocaleesVE,
	_LocaleName[310:315]:      LocaleetEE,
	_LocaleLowerName[310:315]: LocaleetEE,
	_LocaleName[315:320]:      LocalefaIR,
	_LocaleLowerName[315:320]: LocalefaIR,
	_LocaleName[320:325]:      LocalefiFI,
	_LocaleLowerName[320:325]: LocalefiFI,
	_LocaleName[325:330]:      LocalefilPH,
	_LocaleLowerName[325:330]: LocalefilPH,
	_LocaleName[330:335]:      LocalefrBE,
	_LocaleLowerName[330:335]: LocalefrBE,
	_LocaleName[335:340]:      LocalefrCA,
	_LocaleLowerName[335:340]: LocalefrCA,
	_LocaleName[340:345]:      LocalefrCH,
	_LocaleLowerName[340:345]: LocalefrCH,
	_LocaleName[345:350]:      LocalefrFR,
	_LocaleLowerName[345:350]: LocalefrFR,
	_LocaleName[350:355]:      LocalegaIE,
	_LocaleLowerName[350:355]: LocalegaIE,
	_LocaleName[355:360]:      LocaleglES,
	_LocaleLowerName[355:360]: LocaleglES,
	_LocaleName[360:365]:      LocaleguIN,
	_LocaleLowerName[360:365]: LocaleguIN,
	_LocaleName[365:370]:      LocaleheIL,
	_LocaleLowerName[365:370]: LocaleheIL,
	_LocaleName[370:375]:      LocalehiIN,
	_LocaleLowerName[370:375]: LocalehiIN,
	_LocaleName[375:380]:      LocalehrHR,
	_LocaleLowerName[375:380]: LocalehrHR,
	_LocaleName[380:385]:      LocalehuHU,
	_LocaleLowerName[380:385]: LocalehuHU,
	_LocaleName[385:390]:      LocaleidID,
	_LocaleLowerName[385:390]: LocaleidID,
	_LocaleName[390:395]:      LocaleitIT,
	_LocaleLowerName[390:395]: LocaleitIT,
	_LocaleName[395:400]:      LocalejaJP,
	_LocaleLowerName[395:400]: LocalejaJP,
	_LocaleName[400:405]:      LocalejvID,
	_LocaleLowerName[400:405]: LocalejvID,
	_LocaleName[405:410]:      LocalekmKH,
	_LocaleLowerName[405:410]: LocalekmKH,
	_LocaleName[410:415]:      LocalekoKR,
	_LocaleLowerName[410:415]: LocalekoKR,
	_LocaleName[415:420]:      LocaleltLT,
	_LocaleLowerName[415:420]: LocaleltLT,
	_LocaleName[420:425]:      LocalelvLV,
	_LocaleLowerName[420:425]: LocalelvLV,
	_LocaleName[425:430]:      LocalemrIN,
	_LocaleLowerName[425:430]: LocalemrIN,
	_LocaleName[430:435]:      LocalemsMY,
	_LocaleLowerName[430:435]: LocalemsMY,
	_LocaleName[435:440]:      LocalemtMT,
	_LocaleLowerName[435:440]: LocalemtMT,
	_LocaleName[440:445]:      LocalemyMM,
	_LocaleLowerName[440:445]: LocalemyMM,
	_LocaleName[445:450]:      LocalenbNO,
	_LocaleLowerName[445:450]: LocalenbNO,
	_LocaleName[450:455]:      LocalenlBE,
	_LocaleLowerName[450:455]: LocalenlBE,
	_LocaleName[455:460]:      LocalenlNL,
	_LocaleLowerName[455:460]: LocalenlNL,
	_LocaleName[460:465]:      LocaleplPL,
	_LocaleLowerName[460:465]: LocaleplPL,
	_LocaleName[465:470]:      LocaleptBR,
	_LocaleLowerName[465:470]: LocaleptBR,
	_LocaleName[470:475]:      LocaleptPT,
	_LocaleLowerName[470:475]: LocaleptPT,
	_LocaleName[475:480]:      LocaleroRO,
	_LocaleLowerName[475:480]: LocaleroRO,
	_LocaleName[480:485]:      LocaleruRU,
	_LocaleLowerName[480:485]: LocaleruRU,
	_LocaleName[485:490]:      LocaleskSK,
	_LocaleLowerName[485:490]: LocaleskSK,
	_LocaleName[490:495]:      LocaleslSI,
	_LocaleLowerName[490:495]: LocaleslSI,
	_LocaleName[495:500]:      LocalesoSO,
	_LocaleLowerName[495:500]: LocalesoSO,
	_LocaleName[500:505]:      LocalesuID,
	_LocaleLowerName[500:505]: LocalesuID,
	_LocaleName[505:510]:      LocalesvSE,
	_LocaleLowerName[505:510]: LocalesvSE,
	_LocaleName[510:515]:      LocaleswKE,
	_LocaleLowerName[510:515]: LocaleswKE,
	_LocaleName[515:520]:      LocaleswTZ,
	_LocaleLowerName[515:520]: LocaleswTZ,
	_LocaleName[520:525]:      LocaletaIN,
	_LocaleLowerName[520:525]: LocaletaIN,
	_LocaleName[525:530]:      LocaletaLK,
	_LocaleLowerName[525:530]: LocaletaLK,
	_LocaleName[530:535]:      LocaletaSG,
	_LocaleLowerName[530:535]: LocaletaSG,
	_LocaleName[535:540]:      LocaleteIN,
	_LocaleLowerName[535:540]: LocaleteIN,
	_LocaleName[540:545]:      LocalethTH,
	_LocaleLowerName[540:545]: LocalethTH,
	_LocaleName[545:550]:      LocaletrTR,
	_LocaleLowerName[545:550]: LocaletrTR,
	_LocaleName[550:555]:      LocaleukUA,
	_LocaleLowerName[550:555]: LocaleukUA,
	_LocaleName[555:560]:      LocaleurIN,
	_LocaleLowerName[555:560]: LocaleurIN,
	_LocaleName[560:565]:      LocaleurPK,
	_LocaleLowerName[560:565]: LocaleurPK,
	_LocaleName[565:570]:      LocaleuzUZ,
	_LocaleLowerName[565:570]: LocaleuzUZ,
	_LocaleName[570:575]:      LocaleviVN,
	_LocaleLowerName[570:575]: LocaleviVN,
	_LocaleName[575:580]:      LocalezhCN,
	_LocaleLowerName[575:580]: LocalezhCN,
	_LocaleName[580:585]:      LocalezhHK,
	_LocaleLowerName[580:585]: LocalezhHK,
	_LocaleName[585:590]:      LocalezhTW,
	_LocaleLowerName[585:590]: LocalezhTW,
	_LocaleName[590:595]:      LocalezuZA,
	_LocaleLowerName[590:595]: LocalezuZA,
}

var _LocaleNames = []string{
	_LocaleName[0:5],
	_LocaleName[5:10],
	_LocaleName[10:15],
	_LocaleName[15:20],
	_LocaleName[20:25],
	_LocaleName[25:30],
	_LocaleName[30:35],
	_LocaleName[35:40],
	_LocaleName[40:45],
	_LocaleName[45:50],
	_LocaleName[50:55],
	_LocaleName[55:60],
	_LocaleName[60:65],
	_LocaleName[65:70],
	_LocaleName[70:75],
	_LocaleName[75:80],
	_LocaleName[80:85],
	_LocaleName[85:90],
	_LocaleName[90:95],
	_LocaleName[95:100],
	_LocaleName[100:105],
	_LocaleName[105:110],
	_LocaleName[110:115],
	_LocaleName[115:120],
	_LocaleName[120:125],
	_LocaleName[125:130],
	_LocaleName[130:135],
	_LocaleName[135:140],
	_LocaleName[140:145],
	_LocaleName[145:150],
	_LocaleName[150:155],
	_LocaleName[155:160],
	_LocaleName[160:165],
	_LocaleName[165:170],
	_LocaleName[170:175],
	_LocaleName[175:180],
	_LocaleName[180:185],
	_LocaleName[185:190],
	_LocaleName[190:195],
	_LocaleName[195:200],
	_LocaleName[200:205],
	_LocaleName[205:210],
	_LocaleName[210:215],
	_LocaleName[215:220],
	_LocaleName[220:225],
	_LocaleName[225:230],
	_LocaleName[230:235],
	_LocaleName[235:240],
	_LocaleName[240:245],
	_LocaleName[245:250],
	_LocaleName[250:255],
	_LocaleName[255:260],
	_LocaleName[260:265],
	_LocaleName[265:270],
	_LocaleName[270:275],
	_LocaleName[275:280],
	_LocaleName[280:285],
	_LocaleName[285:290],
	_LocaleName[290:295],
	_LocaleName[295:300],
	_LocaleName[300:305],
	_LocaleName[305:310],
	_LocaleName[310:315],
	_LocaleName[315:320],
	_LocaleName[320:325],
	_LocaleName[325:330],
	_LocaleName[330:335],
	_LocaleName[335:340],
	_LocaleName[340:345],
	_LocaleName[345:350],
	_LocaleName[350:355],
	_LocaleName[355:360],
	_LocaleName[360:365],
	_LocaleName[365:370],
	_LocaleName[370:375],
	_LocaleName[375:380],
	_LocaleName[380:385],
	_LocaleName[385:390],
	_LocaleName[390:395],
	_LocaleName[395:400],
	_LocaleName[400:405],
	_LocaleName[405:410],
	_LocaleName[410:415],
	_LocaleName[415:420],
	_LocaleName[420:425],
	_LocaleName[425:430],
	_LocaleName[430:435],
	_LocaleName[435:440],
	_LocaleName[440:445],
	_LocaleName[445:450],
	_LocaleName[450:455],
	_LocaleName[455:460],
	_LocaleName[460:465],
	_LocaleName[465:470],
	_LocaleName[470:475],
	_LocaleName[475:480],
	_LocaleName[480:485],
	_LocaleName[485:490],
	_LocaleName[490:495],
	_LocaleName[495:500],
	_LocaleName[500:505],
	_LocaleName[505:510],
	_LocaleName[510:515],
	_LocaleName[515:520],
	_LocaleName[520:525],
	_LocaleName[525:530],
	_LocaleName[530:535],
	_LocaleName[535:540],
	_LocaleName[540:545],
	_LocaleName[545:550],
	_LocaleName[550:555],
	_LocaleName[555:560],
	_LocaleName[560:565],
	_LocaleName[565:570],
	_LocaleName[570:575],
	_LocaleName[575:580],
	_LocaleName[580:585],
	_LocaleName[585:590],
	_LocaleName[590:595],
}

// LocaleString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func LocaleString(s string) (Locale, error) {
	if val, ok := _LocaleNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _LocaleNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Locale values", s)
}

// LocaleValues returns all values of the enum
func LocaleValues() []Locale {
	return _LocaleValues
}

// LocaleStrings returns a slice of all String values of the enum
func LocaleStrings() []string {
	strs := make([]string, len(_LocaleNames))
	copy(strs, _LocaleNames)
	return strs
}

// IsALocale returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Locale) IsALocale() bool {
	for _, v := range _LocaleValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Locale
func (i Locale) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Locale
func (i *Locale) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Locale should be a string, got %s", data)
	}

	var err error
	*i, err = LocaleString(s)
	return err
}
